// <auto-generated />
using LuisDelValle.TimesheetSolution.WebApi.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LuisDelValle.TimesheetSolution.WebApi.Migrations
{
    [DbContext(typeof(TimesheetDbContext))]
    [Migration("20180604133536_addingTimesheetAndEmployeeTables")]
    partial class addingTimesheetAndEmployeeTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LuisDelValle.TimesheetSolution.WebApi.Models.Timesheet", b =>
                {
                    b.Property<int>("TimesheetId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("EmployeeId");

                    b.Property<double>("Hours");

                    b.HasKey("TimesheetId");

                    b.ToTable("Timesheets");
                });
#pragma warning restore 612, 618
        }
    }
}
